#include <iostream>
#include <cstdio>
#include <string>
#include <cmath>
#include <cstdlib>
#include <ios>
#include <vector>
#include <fstream>
#include <map>
#include <algorithm>
#include <QString>
#include <sstream>
#include "pocketfft_hdronly.h"
